# Generated by Django 5.0.1 on 2024-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmilemodel',
            name='best_smile_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersmilemodel',
            name='best_smile_day',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
