# Generated by Django 5.0.1 on 2024-01-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usersmilemodel_best_smile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmilemodel',
            name='best_smile_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
