# Generated by Django 5.0.1 on 2024-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usersmilemodel_best_smile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmilemodel',
            name='best_smile_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
