# Generated by Django 5.0.1 on 2024-01-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usersmilemodel_best_smile_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_detail', models.CharField(max_length=300)),
                ('activity_about', models.CharField(max_length=600)),
            ],
        ),
    ]
