# Generated by Django 5.0.1 on 2024-01-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activitiesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200)),
            ],
        ),
    ]
